###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
####consul注册中心地址
  cloud:
    consul:
      host: 192.168.125.7
      port: 8500
      discovery:
        #hostname: 192.168.125.7
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
